### PR TITLE
Remove Extra TimeUpdate

### PR DESCRIPTION
**Pull request by Denoder**

### CODE REVIEW

**Comment by ThaUnknown** [comment]
thanks for the pr

the entire js wrapper for the SO worker is a fucking shitstorm, I'm re-writing it from scratch, so this isn't really required

**Comment by Denoder** [comment]
I saw that libass took on the project now, so its probably 30% less dead now: https://github.com/libass/JavascriptSubtitlesOctopus

**Comment by ThaUnknown** [comment]
> I saw that libass took on the project now, so its probably 30% less dead now: https://github.com/libass/JavascriptSubtitlesOctopus

yeah, I know, but I used [DataHoarder's](https://github.com/WeebDataHoarder/JavascriptSubtitlesOctopus) version, and then built on top of it with my own improvements, we were meant to commit our changes to libass but haven't bothered yet

**Comment by ThaUnknown** [comment]
this has been fixed by my re-write of SO
https://github.com/ThaUnknown/webtorrent-player/commit/08b6d630b1155539cda49cc4a83d5ea18d32a032

**Pull request closed without merging**
