### PR TITLE
Fixed Typo: kB to KB

### PR DESCRIPTION
**Pull request by combe15**
Fixed a typo for the abbreviation KiloBytes.

### CODE REVIEW

**Comment by Kirdow** [comment]
Writing kilobytes as KB with capital K is only really considered when dividing by 1024. If you're dividing by 1000 like when you use the metric scale, as this code is currently doing, you're generally writing it as kB rather than KB. So in that regard, there is no typo here.

Source: https://en.wikipedia.org/wiki/Kilobyte

**Comment by ThaUnknown** [comment]
> Writing kilobytes as KB with capital K is only really considered when dividing by 1024. If you're dividing by 1000 like when you use the metric scale, as this code is currently doing, you're generally writing it as kB rather than KB. So in that regard, there is no typo here.
> 
> Source: https://en.wikipedia.org/wiki/Kilobyte

tru, but kB look bad

**Comment by combe15** [comment]
#changethestandard
It's dumb and nobody truly follows it anyways. it's close enough IMO. nobody is going to bat an eye at missing 24 bytes in this case.
Even this popular education platform talking about the sizes gets the abbreviation wrong.
[www.geeksforgeeks.org/understanding-file-sizes](https://www.geeksforgeeks.org/understanding-file-sizes-bytes-kb-mb-gb-tb-pb-eb-zb-yb/)
The standard should be that Kilobyte == KB and Kibibyte== KiB
The current standard doesn't make intuitive sense and nobody following it doesn't make it much of a standard, now does it?

But that's just my opinion.

**Comment by ThaUnknown** [comment]
> #changethestandard
> It's dumb and nobody truly follows it anyways. it's close enough IMO. nobody is going to bat an eye at missing 24 bytes in this case.
> Even this popular education platform talking about the sizes gets the abbreviation wrong.
> [www.geeksforgeeks.org/understanding-file-sizes](https://www.geeksforgeeks.org/understanding-file-sizes-bytes-kb-mb-gb-tb-pb-eb-zb-yb/)
> The standard should be that Kilobyte == KB and Kibibyte== KiB
> The current standard doesn't make intuitive sense and nobody following it doesn't make it much of a standard, now does it?
> 
> But that's just my opinion.

or you could just say "it luk bad" 
winning argument right there.

**Comment by combe15** [comment]
> > #changethestandard
> > It's dumb and nobody truly follows it anyways. it's close enough IMO. nobody is going to bat an eye at missing 24 bytes in this case.
> > Even this popular education platform talking about the sizes gets the abbreviation wrong.
> > [www.geeksforgeeks.org/understanding-file-sizes](https://www.geeksforgeeks.org/understanding-file-sizes-bytes-kb-mb-gb-tb-pb-eb-zb-yb/)
> > The standard should be that Kilobyte == KB and Kibibyte== KiB
> > The current standard doesn't make intuitive sense and nobody following it doesn't make it much of a standard, now does it?
> > But that's just my opinion.
> 
> or you could just say "it luk bad"
> winning argument right there.

It looks bad and I don't like it.

**Pull request merged**
